@startuml

class User

class HerokuFacade{
    get_instance(client_type)
    client_instance = get_instance(client_type)
}

class WeatherClient{
    request
    response
}

class DivinationClient{
    request
    response
}

class LineClient{
    request
    response
}

class GoogleClient{
    request
    response
    make_schedule
}

class HttpClient{
    request
    response
}


User -- HerokuFacade
HerokuFacade o-- WeatherClient
HerokuFacade o-- DivinationClient
HerokuFacade o-- LineClient
HerokuFacade o-- GoogleClient

@enduml
